const APP_CONFIG = {
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  API_TIMEOUT: process.env.EXPO_PUBLIC_API_TIMEOUT,
  DEBUG: process.env.EXPO_PUBLIC_DEBUG !== 'false',
  ENABLE_ANALYTICS: process.env.EXPO_PUBLIC_ENABLE_ANALYTICS === 'true',
  ENABLE_CRASH_REPORTING: process.env.EXPO_PUBLIC_ENABLE_CRASH_REPORTING !== 'false',
  ENV: process.env.EXPO_PUBLIC_ENV,
  PRIVACY_EMAIL: process.env.EXPO_PUBLIC_PRIVACY_EMAIL,
  SUPPORT_EMAIL: process.env.EXPO_PUBLIC_SUPPORT_EMAIL,
  OFFICE_ADDRESS: process.env.EXPO_PUBLIC_OFFICE_ADDRESS
};

export default APP_CONFIG;